---
default:
  tags:
    - k8s-aws-tools
  interruptible: true

include:
  - project: 'kxdev/shared-tools/ci-templates'
    ref: main
    file:
      - 'insights/whitesource.yaml'
      - 'insights/test.yaml'
      - 'security/security.yaml'
      - 'deploy/record-results.yml'
      - "insights/data-science/common.yaml"

stages:
  - build
  - test
  - visualisation
  - report-results
  - sonarqube
  - publish
  - docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  KX_PIP_EXTRA_INSTALL_URL: "https://${INT_NEXUS_USER_RW}:${INT_NEXUS_PASS_RW}@${INSIGHTS_DEV_NEXUS_URL_NOPREFIX}/repository/kxi/simple"
  PIP_ROOT_USER_ACTION: ignore
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHONUNBUFFERED: 1

cache:
  paths:
    - .cache/pip
  key: "$CI_JOB_NAME"

.default-rules:
  rules:
    - !reference [.pakxcli-integration-rules, rules]
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_MERGE_REQUEST_IID

build:wheel:
  stage: build
  image: python:3
  rules:
    - !reference [ .default-rules, rules ]
  before_script:
    - python3 -m pip config set install.extra-index-url "${KX_PIP_EXTRA_INSTALL_URL}"
    - python3 -m pip install --upgrade build
  script:
    - SETUPTOOLS_SCM_DEBUG=1 python3 -m build
  artifacts:
    paths:
      - dist

.unit-tests:
  stage: test
  image: python:3
  rules:
    - !reference [ .default-rules, rules ]
  before_script:
    - python3 -m pip config set install.extra-index-url "${KX_PIP_EXTRA_INSTALL_URL}"
    - pip install .[dev]
    - pip install dist/*.whl
    - export KUBECONFIG=$(pwd)/tests/files/test-kube-config
  script:
    - ./test-and-coverage.sh unit
  artifacts:
    paths:
      - htmlcov
      - report.unit.xml
      - coverage.unit.xml
      - .coverage.unit

integration-tests:
  stage: test
  rules:
    - !reference [ .default-rules, rules ]
  image:
    name: python:3.10
  before_script:
    - python3 -m pip config set install.extra-index-url "${KX_PIP_EXTRA_INSTALL_URL}"
    - pip install .[dev]
    - pip install dist/*.whl
    - mkdir -p /root/.insights
    - cp tests/files/integration-cli-config /root/.insights/cli-config
    - echo "admin.password = $KEYCLOAK_ADMIN_PASSWORD" >> /root/.insights/cli-config
  script:
    - ./test-and-coverage.sh integration
  artifacts:
    paths:
      - htmlcov
      - report.integration.xml
      - coverage.integration.xml
      - .coverage.integration

combine-test-metrics:
  stage: visualisation
  rules:
    - !reference [ .default-rules, rules ]
  image:
    name: python:3.10
  before_script:
    - python3 -m pip config set install.extra-index-url "${KX_PIP_EXTRA_INSTALL_URL}"
    - pip install .[dev]
    - pip install junitparser
  script:
    # combines coverage data files named .coverage.* and output a new xml report
    - coverage combine
    - coverage report
    - coverage xml
    # merges multiple junit xml files into one file
    - junitparser merge report.unit.xml report.integration.xml report.xml
  coverage: /^TOTAL.*\s+(\d+%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
    paths:
      - coverage.xml
  needs:
    - unit-tests-3.8
    - integration-tests

whitesource-dep-scan:
  stage: test
  extends:
    - .whitesource-scan
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    KUBERNETES_MEMORY_REQUEST: "600Mi"
    KUBERNETES_MEMORY_LIMIT: "1Gi"
    WS_PRODUCTNAME: "insights"
    WS_PRODUCTVERSION: "main"
    WS_PROJECTNAME: "$CI_PROJECT_NAME"
    WS_PROJECTVERSION: "$CI_DEFAULT_BRANCH"

whitesource-release-dep-scan:
  stage: test
  extends:
    - .whitesource-scan
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /release\/.*/
  before_script:
      - |
        export WS_PRODUCTVERSION="${CI_COMMIT_REF_NAME#*/}"
        export WS_PROJECTVERSION="${CI_COMMIT_REF_NAME#*/}"
  variables:
    WS_PRODUCTNAME: "insights"
    WS_PROJECTNAME: "$CI_PROJECT_NAME"
    KUBERNETES_MEMORY_REQUEST: "600Mi"
    KUBERNETES_MEMORY_LIMIT: "1Gi"

unit-tests-3.8:
  extends: .unit-tests
  image: python:3.8

unit-tests-3.9:
  extends: .unit-tests
  image: python:3.9

unit-tests-3.10:
  extends: .unit-tests
  image: python:3.10

pytest-kpis:
  stage: visualisation
  needs:
    - combine-test-metrics
  variables:
    ARTIFACT_PATH: "$CI_PROJECT_DIR/coverage.xml"
  extends: .extract-pytest-kpis
  rules:
    - !reference [.default-rules, rules]
  allow_failure: true

send-report-to-insights:
  stage: report-results
  extends: .record-results
  rules:
    - !reference [.default-rules, rules]
  allow_failure: true

publish package:
  stage: publish
  image: python:3
  variables:
    PYPI_URL: "$INSIGHTS_DEV_NEXUS_URL"
    TWINE_USERNAME: "$INT_NEXUS_USER_RW"
    TWINE_PASSWORD: "$INT_NEXUS_PASS_RW"
  before_script:
    - python -m pip install --upgrade twine
  script:
    - python -m twine upload  --non-interactive --repository-url "${PYPI_URL}/repository/kxi/" dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG

publish package external kxi-pypi-public:
  stage: publish
  image: python:3
  variables:
    PYPI_URL: "$INSIGHTS_PROD_NEXUS_URL"
    TWINE_USERNAME: "$EXT_NEXUS_USER_RW"
    TWINE_PASSWORD: "$EXT_NEXUS_PASS_RW"
  before_script:
    - python -m pip install --upgrade twine
  script:
    - python -m twine upload  --non-interactive --repository-url "${PYPI_URL}/repository/kxi-pypi-public/" dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

pages:merge-request:
  image: python:3.8
  stage: docs
  variables:
    PREVIEW_ROOT: "https://kxdev.gitlab.io/-/kxinsights/kxi-cli"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: "$PREVIEW_ROOT/-/jobs/$CI_JOB_ID/artifacts/public/cli/index.html"
    auto_stop_in: 3 days
  before_script:
    - python3 -m pip config set install.extra-index-url "${KX_PIP_EXTRA_INSTALL_URL}"
    - pip install .[doc]
  script:
    - mkdocs build --strict
    - mv site public/
  artifacts:
    paths:
      - public
  rules:
    # Run job on Merge Request
    - if: $CI_MERGE_REQUEST_ID

pages:
  image: python:3.8
  stage: docs
  variables:
    PREVIEW_ROOT: "https://kxdev.gitlab.io/-/kxinsights/kxi-cli"
  environment:
    name: main
    url: "$PREVIEW_ROOT/-/jobs/$CI_JOB_ID/artifacts/public/cli/index.html"
  before_script:
    - python3 -m pip config set install.extra-index-url "${KX_PIP_EXTRA_INSTALL_URL}"
    - pip install .[doc]
  script:
    - mkdocs build --strict
    - mv site public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sonarqube-check:
  stage: sonarqube
  extends: .sonar-template
  needs:
    - unit-tests-3.8
    - integration-tests
  rules:
    - !reference [ .default-rules, rules ]

spell-check:
  stage: test
  extends:
    - .cspell
  rules:
    - !reference [ .default-rules, rules ]
  script:
    - cspell "kxicli/**/*.py"
