stages:
  - build
  - test
  - publish
  - docs

# Run stages on internal gitlab-runner
default:
  tags:
    - kxi-gitlab-runner

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
  key: "$CI_JOB_NAME"

build dist:
  stage: build
  image: python:3
  script:
    - python3 -m pip install --upgrade build
    - python3 -m build
  artifacts:
    paths:
      - dist

.run-tests:
  stage: test
  image: python:3
  script:
    - pip install -r kxicli/tests/requirements.txt
    - pip install dist/*.whl
    - export KUBECONFIG=$(pwd)/kxicli/tests/files/test-kube-config
    - coverage run -m pytest
    - coverage report
    - coverage html
    - coverage xml
  artifacts:
    paths:
      - htmlcov
    reports:
      cobertura: coverage.xml

run tests 3.6:
    extends: .run-tests
    image: python:3.6

run tests 3.7:
    extends: .run-tests
    image: python:3.7

run tests 3.8:
    extends: .run-tests
    image: python:3.8

run tests 3.9:
    extends: .run-tests
    image: python:3.9

run tests 3.10:
    extends: .run-tests
    image: python:3.10

publish package:
  stage: publish
  image: python:3
  variables:
    PYPI_URL: "https://nexus.internal-insights.kx.com/repository/kxi-cli/"
    TWINE_USERNAME: "$NEXUS_INTERNAL_USERNAME"
    TWINE_PASSWORD: "$NEXUS_INTERNAL_PASSWORD"
  script:
    - python -m pip install --upgrade twine
    - python -m twine upload  --non-interactive --repository-url  "$PYPI_URL" dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG

pages:
  image: python:3.8
  stage: docs
  script:
    - pip install -r mkdocs.requirements
    - pip install .
    # can potentially remove this export when kxi-5994 is implemented
    - export KUBECONFIG=$(pwd)/kxicli/tests/files/test-kube-config
    - mkdocs build --strict
    - mv site public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: manual
      allow_failure: true
